version: '3.3'
services:
  backend:
    build:  
      context: .
      dockerfile: dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    extra_hosts:
      - "docker.for.linux.localhost:172.17.0.1"
    volumes:
      - .:/app
    depends_on:
      - db

  

  db:
   image: postgres:13.1
   environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust
   volumes:
   - .dbdata:/var/lib/postgres
   ports:
   - 5432:5432
